### ISSUE TITLE
Don't show up

### ISSUE THREAD

**Issue by subdesign** [zpm-zsh/pr-php#1]
Using this plugin I get only a `-php` text in the prompt.

<img width="517" alt="Screenshot 2022-06-24 at 10 54 56" src="https://user-images.githubusercontent.com/691695/175500961-66b99d28-54a6-4ee3-a30b-94d7580e7c4a.png">

theme code line:
`RPROMPT='%(?.✔.%{$fg[red]%}✘%f) $(node_prompt_version) $pr-php'`

Installed the _colors_ and _helpers_ plugins, and added to plugins=() list in _.zshrc_ file.
Zsh version: zsh 5.8 (x86_64-apple-darwin20.0)
MacOS Big Sur

**Comment by subdesign** [comment]
Nevermind. the package is called `pr-php` , but the command is `pr_php`, so I mixed up the two. now it's working.

**Comment by grigorii-horos** [comment]
@subdesign Hey!

`$pr_php` isn't command, it's a variable. But variable can't contain `-` sign. So, I use `_` as divider
